export const nextDestinations = [
  {
    id: 1,
    cardImageUrl: "/assets/destination1.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 2,
    cardImageUrl: "/assets/destination2.svg",
    imageUrls: ["/assets/nextTrip.svg", "/assets/Home.svg"],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 3,
    cardImageUrl: "/assets/destination3.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 4,
    cardImageUrl: "/assets/destination1.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 5,
    cardImageUrl: "/assets/destination2.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 6,
    cardImageUrl: "/assets/destination3.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 7,
    cardImageUrl: "/assets/destination1.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 8,
    cardImageUrl: "/assets/destination2.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
  {
    id: 9,
    cardImageUrl: "/assets/destination3.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination2.svg",
    ],
    date: "17th Feb",
    weekDay: "wednesday",
    day: "23",
    month: "December",
    year: "2024",
    price: "1600 DZD",
    title: "lac vert de yakoren tizi-ouzou",
    duration: "One Day",
    overview:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo conDuis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatu",
    important: ["+17", "sking", "guide"],
    departurePlace: "Main Square, Old Town",
    departureTime: "Approximately 8.30AM",
    returnTime: "Approximately 7.30PM",
    dressCode: "Casual, comfortable and light",
    included: ["Personal Guide", "Breakfast", "Bus Transfer", "lunch"],
    program: [
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
      [
        "5 Star Accommodation",
        "Breakfast",
        "5 Star Accommodation",
        "Breakfast",
      ],
    ],
  },
];
export const experiences = [
  {
    id: 10,
    imageUrl: "/assets/experience1.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 11,
    imageUrl: "/assets/experience2.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 12,
    imageUrl: "/assets/experience3.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 13,
    imageUrl: "/assets/experience4.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 14,
    imageUrl: "/assets/experience1.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 15,
    imageUrl: "/assets/experience2.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 16,
    imageUrl: "/assets/experience3.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
  {
    id: 17,
    imageUrl: "/assets/experience4.svg",
    imageUrls: [
      "/assets/destination1.svg",
      "/assets/destination2.svg",
      "/assets/destination3.svg",
    ],
    title: "foret des lions - Oran",
    rating: "4.5",
    reviewsNumber: "24",
    travelersNumber: "124",
    distance: "15km",
    highlights: [
      {
        imageUrl: "../../public/assets/highlight1.svg",
        title: "The castle of Bent el Khass",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight2.svg",
        title: "The sunset in the Gour Mountains",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
      {
        imageUrl: "../../public/assets/highlight3.svg",
        title: "music session with guitarist",
        description:
          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore",
      },
    ],
    gallery: [
      "/assets/gallery1.svg",
      "/assets/gallery2.svg",
      "/assets/gallery3.svg",
    ],
  },
];
export const reviews = [
  {
    id: 18,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 19,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 2,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 20,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 21,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 22,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 23,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 24,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 5,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 25,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 1,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 26,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 2,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 27,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 28,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 29,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 30,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 31,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 5,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 32,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 1,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 33,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 2,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 34,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 35,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 36,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 3,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 37,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 4,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
  {
    id: 38,
    imageUrl: "/assets/reviews.svg",
    username: "Unknown",
    rating: 5,
    content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit,",
  },
];
